# ---------------------------------------------------------------------
# skillet preamble information used by panhandler
# unique snippet name
name: SFNDNSPOC
# label used for menu selection
label: TAP Mode PoC for DNS
description: Configure TAP Mode POC for use with SFN 4.0
type: panos
extends:
labels:
  collection:
    - SafeNetworking
# end of preamble section
# ---------------------------------------------------------------------
# variables section
#
variables:
#
# - name: UEIPPool
#   description: IP Pool for own subscribers UE
#   default: 100.64.0.0/16
#   type_hint: text

 - name: SFNServerIP
   description: IP address of SFN Server
   default: 10.0.0.1
   type_hint: ip_address

 - name: TAPNIC
   description: Interface for TAP zone
   default: ethernet1/1
   type_hint: text
#
# ---------------------------------------------------------------------
# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
#
# - name: Objects
#   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
#   file: AddrObject.xml

 - name: SFNServerProfile
   xpath: /config/shared/log-settings/syslog
   file: SFNServerProfile.xml

 - name: Interface
   xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet
   file: TAPNIC.xml

 - name: Zone
   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
   file: Zone.xml

# - name: DiskLogQuotaAndEnableSCTPGTP
#   xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig
#   file: DiskLogQuotaAndEnableSCTPGTP.static.xml
#
# - name: ZoneProtect_IPOnly
#   xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile
#   file: ZoneProtectIPOnly.static.xml
#
# - name: GTPProfile
#   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/gtp
#   file: GTPProfileLogTunnel.static.xml
#
# - name: SCTPProfile
#   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/sctp
#   file: SCTPProfileCommonS6SS7.static.xml
#
# - name: VulnProfile_FloodAndBrute
#   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability
#   file: VulnProfile_FloodAndBrute.static.xml

 - name: SFNForwardingProfile
   xpath: /config/shared/log-settings/profiles
   file: SFNForwardingProfile.static.xml

 #- name: Rules
 #  xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
 #  file: RulesPOCTAPGeneric.xml
